bedroom_choices = {
    '1':1,
    '2':2,
    '3':3,
    '4':4,
    '5':5,
    '6':6,
    '7':7,
    '8':8,
    '9':9,
    '10':10
}

price_choices = {
    '100000':'Ksh100,000',
    '200000':'Ksh200,000',
    '300000':'Ksh300,000',
    '400000':'Ksh400,000',
    '500000':'Ksh500,000',
    '600000':'Ksh600,000',
    '700000':'Ksh700,000',
    '800000':'Ksh800,000',
    '900000':'Ksh900,000',
    '1000000':'Ksh1M+'
}

county_choices = {
    'MSA':'Mombasa',
    'KL':'Kwale',
    'KF':'Kilifi',
    'TR':'Tana River',
    'LMU':'Lamu',
    'TT':'TaitaTaveta',
    'GRS':'Garissa',
    'WJR':'Wajir',
    'MDR':'Mandera',
    'MRS':'Marsabit',
    'IS':'Isiolo',
    'MRU':'Meru',
    'TN':'Tharaka-Nithi',
    'EBU':'Embu',
    'KIT':'Kitui',
    'MCH':'Machakos',
    'MKU':'Makueni',
    'NYD':'Nyandarua',
    'NYI':'Nyeri',
    'KI':'Kirinyaga',
    'MUR':"Murang'a",
    'KBU':'Kiambu',
    'TUR':'Turkana',
    'WP':'West Pokot',
    'SMB':'Samburu',
    'TNZ':'Trans Nzoia',
    'UG':'Uasin Gishu',
    'EM':'Elgeyo Marakwet',
    'NA':'Nandi',
    'BAR':'Baringo',
    'LKP':'Laikipia',
    'NAK':'Nakuru',
    'NRK':'Narok',
    'KJD':'Kajiado',
    'KCO':'Kericho',
    'BOM':'Bomet',
    'KMG':'Kakamega',
    'VH':'Vihiga',
    'BNG':'Bungoma',
    'BU':'Busia',
    'SI':'Siaya',
    'KSM':'Kisumu',
    'HB':'Homa Bay',
    'MGR':'Migori',
    'KSI':'Kisii',
    'NYM':'Nyamira',
    'NRB':'Nairobi'
}